/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Interfaces_Remotas.Servicos_mensagem;
import java.rmi.Naming;

/**
 *
 * @author felipe
 */
public class Enviar extends javax.swing.JFrame {
    
    private String senha, email, dominio;
    
    public String getSenha(){
        return this.senha;
    }
    
    public void setSenha(String senha){
        this.senha = senha;
    }
    
    public String getEmail(){
        return this.email;
    }
    
    public void setEmail(String email){
        this.email = email;
    }
    
    public String getDominio(){
        return this.dominio;
    }
    
    public void setDominio(String dominio){
        this.dominio = dominio;
    }

    /**
     * Creates new form Enviar
     */
    public Enviar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputDestinatario = new javax.swing.JTextField();
        inputAssunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputCorpo = new javax.swing.JTextArea();
        botaoEnviar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Destinatário:");

        jLabel3.setText("Assunto:");

        jLabel4.setText("Corpo:");

        jLabel5.setText("Preencha os campos para enviar a mensagem:");

        inputDestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputDestinatarioKeyReleased(evt);
            }
        });

        inputAssunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputAssuntoKeyReleased(evt);
            }
        });

        inputCorpo.setColumns(20);
        inputCorpo.setRows(5);
        inputCorpo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCorpoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(inputCorpo);

        botaoEnviar.setText("Enviar");
        botaoEnviar.setEnabled(false);
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(botaoEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(inputAssunto)
                            .addComponent(inputDestinatario))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        Menu tela = new Menu();
        tela.recebendoDados(this.getEmail(), this.getSenha(), this.getDominio());
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void inputDestinatarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDestinatarioKeyReleased
        if(inputDestinatario.getText().length() > 0 && inputAssunto.getText().length() > 0 && inputCorpo.getText().length() > 0)
            botaoEnviar.setEnabled(true);
        else
            botaoEnviar.setEnabled(false);
    }//GEN-LAST:event_inputDestinatarioKeyReleased

    private void inputAssuntoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAssuntoKeyReleased
        if(inputDestinatario.getText().length() > 0 && inputAssunto.getText().length() > 0 && inputCorpo.getText().length() > 0)
            botaoEnviar.setEnabled(true);
        else
            botaoEnviar.setEnabled(false);
    }//GEN-LAST:event_inputAssuntoKeyReleased

    private void inputCorpoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCorpoKeyReleased
        if(inputDestinatario.getText().length() > 0 && inputAssunto.getText().length() > 0 && inputCorpo.getText().length() > 0)
            botaoEnviar.setEnabled(true);
        else
            botaoEnviar.setEnabled(false);
    }//GEN-LAST:event_inputCorpoKeyReleased

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        
        Servicos_mensagem sdao = null;
        JFrame telinha = new JFrame("Mensagem");
        
        try{
            sdao = (Servicos_mensagem) Naming.lookup("//192.168.0.13/servico_mensagem");
            sdao.enviar(this.getEmail() + this.getDominio(), inputDestinatario.getText(), inputAssunto.getText(), inputCorpo.getText());
            
            Enviar n_tela = new Enviar();
            n_tela.recebendoDados(this.getEmail(), this.getSenha(), this.getDominio());
            JOptionPane.showMessageDialog(telinha, "Mensagem Enviada!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(telinha, e.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enviar().setVisible(true);
            }
        });
    }
    
    public void recebendoDados(String email, String senha, String dominio){
        this.setEmail(email);
        this.setSenha(senha);
        this.setDominio(dominio);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField inputAssunto;
    private javax.swing.JTextArea inputCorpo;
    private javax.swing.JTextField inputDestinatario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
