/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Interfaces_Remotas.Servicos_mensagem;
import java.rmi.Naming;

/**
 *
 * @author felipe
 */
public class ListarMensagem extends javax.swing.JFrame {
    
    private String email, senha, dominio;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    public String getDominio(){
        return this.dominio;
    }
    
    public void setDominio(String dominio){
        this.dominio = dominio;
    }

    /**
     * Creates new form ListarMensagem
     */
    public ListarMensagem(){
        super("Mensagens");
        initComponents();
        this.setLocationRelativeTo(null);
        botaoExcluir.setEnabled(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outputRemetente = new javax.swing.JTextField();
        outputDestinatario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        outputAssunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputCorpo = new javax.swing.JTextArea();
        botaoVoltar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mensagemLista = new javax.swing.JComboBox<>();
        botaoAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Remetente:");

        jLabel2.setText("Destinatário:");

        outputRemetente.setBackground(new java.awt.Color(0, 0, 0));
        outputRemetente.setEnabled(false);
        outputRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputRemetenteActionPerformed(evt);
            }
        });

        outputDestinatario.setBackground(new java.awt.Color(0, 0, 0));
        outputDestinatario.setEnabled(false);

        jLabel3.setText("Assunto:");

        outputAssunto.setBackground(new java.awt.Color(0, 0, 0));
        outputAssunto.setEnabled(false);

        jLabel4.setText("Corpo:");

        outputCorpo.setBackground(new java.awt.Color(0, 0, 0));
        outputCorpo.setColumns(20);
        outputCorpo.setRows(5);
        outputCorpo.setEnabled(false);
        jScrollPane1.setViewportView(outputCorpo);

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecione uma mensagem para lê-la ou apagá-la:");

        jLabel6.setText("Selecionar:");

        mensagemLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mensagemLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mensagemListaItemStateChanged(evt);
            }
        });

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outputAssunto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputDestinatario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputRemetente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensagemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mensagemLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(outputAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputRemetenteActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        Menu tela = new Menu();
        tela.recebendoDados(this.getEmail(),this.getSenha(),this.getDominio());
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void mensagemListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mensagemListaItemStateChanged
        
        Servicos_mensagem sdao = null;
        String dados, remetente = "", destinatario = "", assunto = "", corpo = "";
        Boolean estado1 = false, estado2 = false;
        int cont = 0;
        
        try{
         
            sdao = (Servicos_mensagem) Naming.lookup("//192.168.0.13/servico_mensagem");
            
            dados = sdao.Capturar(mensagemLista.getSelectedItem().toString());
            
            for(int i = 0; i < dados.length(); i++){
                
                if(dados.charAt(i)=='|'){
                    cont++;
                    
                    if(cont==1)
                    {estado1 = false; estado2 = true;}
                    
                    if(cont==2)
                    {estado1 = true; estado2 = false;}
                    
                    if(cont==3)
                    {estado1 = true; estado2 = true;}
                    continue;
                }
                
                if(estado1 == false && estado2 == false)
                    remetente += dados.charAt(i);
                
                if(estado1 == false && estado2 == true)
                    destinatario += dados.charAt(i);
                    
                if(estado1 == true && estado2 == false)
                    assunto += dados.charAt(i);
                
                if(estado1 && estado2)
                    corpo += dados.charAt(i);
                    
            }
            
            outputRemetente.setText(remetente);
            outputDestinatario.setText(destinatario);
            outputAssunto.setText(assunto);
            outputCorpo.setText(corpo);
            
            if(mensagemLista.getSelectedItem().toString().equals(""))
                botaoExcluir.setEnabled(false);
            else
                botaoExcluir.setEnabled(true);
        }
        catch(Exception e){
            JFrame frame = new JFrame("Erro");
            JOptionPane.showMessageDialog(frame, e.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_mensagemListaItemStateChanged

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        
        Servicos_mensagem mdao = null;
        String email_completoD = outputDestinatario.getText();
        String email_completoR = outputRemetente.getText();
        
        try{
            
            mdao = (Servicos_mensagem) Naming.lookup("//192.168.0.13/servico_mensagem");
            
            String  dominioD = "", email_tratadoD = "";
            String  dominioR = "", email_tratadoR = "";
            boolean estado = false;
        
            for(int i = 0; i < email_completoD.length(); i++)
            {
                if(email_completoD.charAt(i)=='@')
                    estado = true;
            
                if(estado)
                    dominioD += email_completoD.charAt(i);
                else
                    email_tratadoD += email_completoD.charAt(i);
            }
            
            estado = false;
        
            for(int i = 0; i < email_completoR.length(); i++)
            {
                if(email_completoR.charAt(i)=='@')
                    estado = true;
            
                if(estado)
                    dominioR += email_completoR.charAt(i);
                else
                    email_tratadoR += email_completoR.charAt(i);
            }
            
            mdao.excluir(dominioR, email_tratadoR, dominioD, email_tratadoD, outputCorpo.getText());
            
            ListarMensagem n_tela = new ListarMensagem();
            n_tela.recebendoDados(this.getEmail(), this.getSenha(), this.getDominio());
            this.dispose();
            
            JFrame frame = new JFrame("Sucesso");
            JOptionPane.showMessageDialog(frame, "A mensagem foi excluida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
           
        }
        catch(Exception e){
            JFrame frame = new JFrame("Erro");
            JOptionPane.showMessageDialog(frame, e.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        ListarMensagem n_tela = new ListarMensagem();
        n_tela.recebendoDados(this.getEmail(), this.getSenha(), this.getDominio());
        this.dispose();
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new ListarMensagem().setVisible(true);
            }
        });
    }
    
    public void recebendoDados(String email, String senha, String dominio){
        this.setEmail(email);
        this.setSenha(senha);
        this.setDominio(dominio);
        MensagensComboBoxModel mensagens_assuntos = new MensagensComboBoxModel(this.getEmail());
        mensagemLista.setModel(mensagens_assuntos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mensagemLista;
    private javax.swing.JTextField outputAssunto;
    private javax.swing.JTextArea outputCorpo;
    private javax.swing.JTextField outputDestinatario;
    private javax.swing.JTextField outputRemetente;
    // End of variables declaration//GEN-END:variables
}
